---
 - hosts: localhost
   become: yes
   ignore_errors: true
   tasks:
     - name: Create a directory
       file:
           path: /var/www/html/protected
           state: directory
           owner: ansible
           group: ansible
           mode:  0755

     - name: create a http.conf file
       file:
         path: "{{ item }}"
         state: touch
         mode: 0755
         owner: ansible
         group: ansible
       with_items:
        - /var/www/html/protected/index.html
        - /var/www/html/protected/httpd.conf
     
     - name: write the contents into http.conf
       lineinfile:
             path: /var/www/html/protected/httpd.conf
             line: "AllowOverride None"
             line: "Changes made here will be deleted"
    
     - name: Replace function
       replace:
           path: /var/www/html/protected/httpd.conf
           regexp: 'AllowOverride None'
           replace: 'AllowOverride Authconfig'
           backup: yes

     - name: write the contents into index.html
       lineinfile:
             path: /var/www/html/protected/index.html
             line: "{{ansible_hostname}} has been customized using Ansible on {{ansible_date_time.date}}"
     - name: restart httpd
       service: 
         name: httpd
         state: restarted
         enabled: yes
